# Author      : Amisha Prashar
# Description : CI/CD Pipeline for building and pushing Docker images to Docker Hub.
# Usage       : Triggered on push to the "main" branch.
# Version     : 1.0.1

name: Lenscorp Workflow

on:
  push:
    branches: [ "main" ] 

jobs:
  Build_and_Push:
    runs-on: ubuntu-22.04

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    # Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # Install Docker Compose and curl
    - name: Install Docker Compose and curlbackend_1.1.0
      run: |
        sudo apt update
        sudo apt install docker-compose curl -y

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push backend image
    - name: Build and push backend
      run: |
        docker build -t amishaprashar22/lens-app:backend_1.2.0 ./backend
        docker push amishaprashar22/lens-app:backend_1.2.0

    # Build and push nginx image
    - name: Build and push nginx
      run: |
        docker build -t amishaprashar22/lens-app:nginx_1.2.0 ./nginx
        docker push amishaprashar22/lens-app:nginx_1.2.0 

    # Run the application in detached mode
    - name: Run application
      run: |
        docker-compose up --build -d
        
    # Test the application
    - name: Test application
      run: |
        curl 0.0.0.0:5000

    # Stop and clean up containers
    - name: Clean up containers
      run: |
          docker-compose down
